"""foregin keys

Revision ID: 09a6bdd4e371
Revises: 715577af4f83
Create Date: 2025-09-20 23:57:42.623320

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "09a6bdd4e371"
down_revision: Union[str, Sequence[str], None] = "715577af4f83"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "requests", sa.Column("user_id", sa.Integer(), nullable=False)
    )
    op.add_column(
        "requests", sa.Column("books_id", sa.Integer(), nullable=False)
    )
    op.create_foreign_key(None, "requests", "users", ["user_id"], ["id"])
    op.create_foreign_key(
        None,
        "requests",
        "books",
        ["books_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.add_column(
        "users", sa.Column("requests_id", sa.Integer(), nullable=False)
    )
    op.create_foreign_key(None, "users", "requests", ["requests_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="foreignkey")
    op.drop_column("users", "requests_id")
    op.drop_constraint(None, "requests", type_="foreignkey")
    op.drop_constraint(None, "requests", type_="foreignkey")
    op.drop_column("requests", "books_id")
    op.drop_column("requests", "user_id")
    # ### end Alembic commands ###
