"""user (firstname, lastname) to name

Revision ID: 1aea5b64c588
Revises: 09a6bdd4e371
Create Date: 2025-09-21 00:08:01.070885

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1aea5b64c588"
down_revision: Union[str, Sequence[str], None] = "09a6bdd4e371"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("name", sa.String(), nullable=False))
    op.drop_constraint(
        op.f("users_requests_id_fkey"), "users", type_="foreignkey"
    )
    op.drop_column("users", "requests_id")
    op.drop_column("users", "last_name")
    op.drop_column("users", "first_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "first_name", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "last_name", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "requests_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.create_foreign_key(
        op.f("users_requests_id_fkey"),
        "users",
        "requests",
        ["requests_id"],
        ["id"],
    )
    op.drop_column("users", "name")
    # ### end Alembic commands ###
