"""requests table

Revision ID: 715577af4f83
Revises: 7c4accdf1604
Create Date: 2025-09-20 21:16:11.855178

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "715577af4f83"
down_revision: Union[str, Sequence[str], None] = "7c4accdf1604"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "requests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "accepted",
                "in_queued",
                "awaiting",
                "given",
                "returned",
                name="status",
            ),
            nullable=False,
        ),
        sa.Column("return_by", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("requests")
    op.execute("DROP TYPE IF EXISTS status")
    # ### end Alembic commands ###
