"""books_id to book_id

Revision ID: cea044563353
Revises: 1aea5b64c588
Create Date: 2025-09-21 10:55:33.268758

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cea044563353"
down_revision: Union[str, Sequence[str], None] = "1aea5b64c588"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "requests", sa.Column("book_id", sa.Integer(), nullable=False)
    )
    op.drop_constraint(
        op.f("requests_books_id_fkey"), "requests", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "requests",
        "books",
        ["book_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.drop_column("requests", "books_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "requests",
        sa.Column(
            "books_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint(None, "requests", type_="foreignkey")
    op.create_foreign_key(
        op.f("requests_books_id_fkey"),
        "requests",
        "books",
        ["books_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.drop_column("requests", "book_id")
    # ### end Alembic commands ###
