"""profile_id to reader_id

Revision ID: 3f79e4e024d1
Revises: 8b81619e5548
Create Date: 2025-11-02 19:51:59.755512

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3f79e4e024d1"
down_revision: Union[str, Sequence[str], None] = "8b81619e5548"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "profiles", sa.Column("reader_id", sa.Integer(), nullable=False)
    )
    op.drop_constraint(
        op.f("profiles_profile_id_fkey"), "profiles", type_="foreignkey"
    )
    op.create_foreign_key(None, "profiles", "readers", ["reader_id"], ["id"])
    op.drop_column("profiles", "profile_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "profiles",
        sa.Column(
            "profile_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint(None, "profiles", type_="foreignkey")
    op.create_foreign_key(
        op.f("profiles_profile_id_fkey"),
        "profiles",
        "readers",
        ["profile_id"],
        ["id"],
    )
    op.drop_column("profiles", "reader_id")
    # ### end Alembic commands ###
