"""update create history 2

Revision ID: 78f4e98bea22
Revises: c105002ae88c
Create Date: 2026-01-03 02:13:54.919445

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "78f4e98bea22"
down_revision: Union[str, Sequence[str], None] = "c105002ae88c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "histories",
        sa.Column(
            "borrowed_at",
            sa.Date(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "histories", sa.Column("borrowed_to", sa.Date(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("histories", "borrowed_to")
    op.drop_column("histories", "borrowed_at")
    # ### end Alembic commands ###
