"""init tables 2

Revision ID: 8b81619e5548
Revises: b5760c518843
Create Date: 2025-11-02 19:17:29.249955

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8b81619e5548"
down_revision: Union[str, Sequence[str], None] = "b5760c518843"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "book_copies",
        sa.Column("serial_num", sa.String(), nullable=False),
        sa.Column("book_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "AVAILABLE", "BORROWED", "RESERVED", name="bookcopystatus"
            ),
            nullable=False,
        ),
        sa.Column("access_type", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["book_id"], ["books.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("serial_num"),
    )
    op.create_table(
        "profiles",
        sa.Column("profile_id", sa.Integer(), nullable=False),
        sa.Column("avatar_url", sa.String(), nullable=True),
        sa.Column("full_name", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["readers.id"],
        ),
        sa.PrimaryKeyConstraint("profile_id"),
    )
    op.create_table(
        "loans",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("reader_id", sa.Integer(), nullable=False),
        sa.Column("copy_id", sa.String(), nullable=False),
        sa.Column("issue_date", sa.DateTime(), nullable=False),
        sa.Column("due_date", sa.DateTime(), nullable=False),
        sa.Column("return_date", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["copy_id"],
            ["book_copies.serial_num"],
        ),
        sa.ForeignKeyConstraint(
            ["reader_id"],
            ["readers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("loans")
    op.drop_table("profiles")
    op.drop_table("book_copies")
    # ### end Alembic commands ###
