"""update tables

Revision ID: 91dd58d8fe69
Revises: 01d49fed9d72
Create Date: 2025-10-12 22:30:21.499004

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "91dd58d8fe69"
down_revision: Union[str, Sequence[str], None] = "01d49fed9d72"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("books", sa.Column("publisher", sa.String(), nullable=False))
    op.drop_constraint(
        op.f("users_personal_id_number_key"), "users", type_="unique"
    )
    op.drop_column("users", "library_card")
    op.drop_column("users", "personal_id_number")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "personal_id_number",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "library_card", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
    )
    op.create_unique_constraint(
        op.f("users_personal_id_number_key"),
        "users",
        ["personal_id_number"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("books", "publisher")
    # ### end Alembic commands ###
