"""chat_id not unique

Revision ID: b1d7880d99ce
Revises: e2bd81e7ba37
Create Date: 2025-10-01 13:59:37.835983

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b1d7880d99ce"
down_revision: Union[str, Sequence[str], None] = "e2bd81e7ba37"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("users_char_id_key"), "users", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("users_char_id_key"),
        "users",
        ["char_id"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
