"""update create history

Revision ID: c105002ae88c
Revises: d28cdabf55ae
Create Date: 2026-01-02 23:49:01.456195

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c105002ae88c"
down_revision: Union[str, Sequence[str], None] = "d28cdabf55ae"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "histories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("copy_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["copy_id"],
            ["book_copies.serial_num"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_constraint(
        op.f("profiles_reader_id_fkey"), "profiles", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "profiles", "readers", ["reader_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "profiles", type_="foreignkey")
    op.create_foreign_key(
        op.f("profiles_reader_id_fkey"),
        "profiles",
        "readers",
        ["reader_id"],
        ["id"],
    )
    op.drop_table("histories")
    # ### end Alembic commands ###
