"""update foreigins

Revision ID: d28cdabf55ae
Revises: 398a513ee255
Create Date: 2025-12-20 19:07:09.719325

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d28cdabf55ae"
down_revision: Union[str, Sequence[str], None] = "398a513ee255"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "loans",
        "issue_date",
        existing_type=sa.DATE(),
        type_=sa.DateTime(),
        existing_nullable=False,
    )
    op.alter_column(
        "loans",
        "due_date",
        existing_type=sa.DATE(),
        type_=sa.DateTime(),
        existing_nullable=False,
    )
    op.alter_column(
        "loans",
        "return_date",
        existing_type=sa.DATE(),
        type_=sa.DateTime(),
        existing_nullable=True,
    )
    op.drop_constraint(op.f("loans_copy_id_fkey"), "loans", type_="foreignkey")
    op.create_foreign_key(
        None,
        "loans",
        "book_copies",
        ["copy_id"],
        ["serial_num"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f("requests_book_id_fkey"), "requests", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "requests", "books", ["book_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "requests", type_="foreignkey")
    op.create_foreign_key(
        op.f("requests_book_id_fkey"), "requests", "books", ["book_id"], ["id"]
    )
    op.drop_constraint(None, "loans", type_="foreignkey")
    op.create_foreign_key(
        op.f("loans_copy_id_fkey"),
        "loans",
        "book_copies",
        ["copy_id"],
        ["serial_num"],
    )
    op.alter_column(
        "loans",
        "return_date",
        existing_type=sa.DateTime(),
        type_=sa.DATE(),
        existing_nullable=True,
    )
    op.alter_column(
        "loans",
        "due_date",
        existing_type=sa.DateTime(),
        type_=sa.DATE(),
        existing_nullable=False,
    )
    op.alter_column(
        "loans",
        "issue_date",
        existing_type=sa.DateTime(),
        type_=sa.DATE(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
