"""users.icon books.cover

Revision ID: d7af9cb5ba7e
Revises: e84f68d8b9dc
Create Date: 2025-10-09 23:32:39.120151

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d7af9cb5ba7e"
down_revision: Union[str, Sequence[str], None] = "e84f68d8b9dc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("books", sa.Column("cover", sa.String(), nullable=True))
    op.add_column("users", sa.Column("icon", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "icon")
    op.drop_column("books", "cover")
    # ### end Alembic commands ###
