"""add icon and cover

Revision ID: e2bd81e7ba37
Revises: 6510cf19c69c
Create Date: 2025-09-30 21:45:20.507611

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e2bd81e7ba37"
down_revision: Union[str, Sequence[str], None] = "6510cf19c69c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("books", sa.Column("cover", sa.String(), nullable=True))
    op.add_column("users", sa.Column("char_id", sa.Integer(), nullable=True))
    op.add_column("users", sa.Column("icon", sa.String(), nullable=True))
    op.create_unique_constraint(None, "users", ["char_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_column("users", "icon")
    op.drop_column("users", "char_id")
    op.drop_column("books", "cover")
    # ### end Alembic commands ###
