"""delete icon cover

Revision ID: e84f68d8b9dc
Revises: b1d7880d99ce
Create Date: 2025-10-05 22:20:46.371490

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e84f68d8b9dc"
down_revision: Union[str, Sequence[str], None] = "b1d7880d99ce"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("books", "cover")
    op.drop_column("users", "icon")
    op.drop_column("users", "char_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("char_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "users",
        sa.Column("icon", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "books",
        sa.Column("cover", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
